<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Vugen" productVer="2020" os="" host="DESKTOP-D80A036"><DocLocation><![CDATA[C:\LoadTests\TruClient2]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[TruClient2]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="21/08/2020 - 09:17:35" eTime="21/08/2020 - 09:17:35" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://test.manage-tlev....tlevels.gov.uk/ was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:38]]></Time>
<TimeTick>1597997858</TimeTick>
<NodeArgs eType="General" icon="0" nRep="9" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Start now button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:40]]></Time>
<TimeTick>1597997860</TimeTick>
<NodeArgs eType="General" icon="0" nRep="10" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.1: Click on Email address textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:41]]></Time>
<TimeTick>1597997861</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Double Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.2: Double click on Email address textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:42]]></Time>
<TimeTick>1597997862</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Double Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.3: Click on Email address textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:43]]></Time>
<TimeTick>1597997863</TimeTick>
<NodeArgs eType="General" icon="0" nRep="13" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.4: Type ao_user_app@tleveltest.com in Email address textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:45]]></Time>
<TimeTick>1597997865</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.5: Click on Password passwordbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:46]]></Time>
<TimeTick>1597997866</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.6: Type ************* in Password passwordbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:47]]></Time>
<TimeTick>1597997867</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.7: Click on Sign in button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:48]]></Time>
<TimeTick>1597997868</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on PEARSON EDUCATION LIMITED...  was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:50]]></Time>
<TimeTick>1597997870</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:51]]></Time>
<TimeTick>1597997871</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Registrations heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:54]]></Time>
<TimeTick>1597997874</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Click on Registrations link was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:55]]></Time>
<TimeTick>1597997875</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Enter the Unique Learner... label exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:56]]></Time>
<TimeTick>1597997876</TimeTick>
<NodeArgs eType="General" icon="0" nRep="22" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[7: Click on Add a new registration link was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:57]]></Time>
<TimeTick>1597997877</TimeTick>
<NodeArgs eType="General" icon="0" nRep="23" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Enter the Unique Learner... textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:58]]></Time>
<TimeTick>1597997878</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Type 8434823482 in Enter the Unique Learner... textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:17:59]]></Time>
<TimeTick>1597997879</TimeTick>
<NodeArgs eType="General" icon="0" nRep="25" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Enter the learner's name heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:01]]></Time>
<TimeTick>1597997881</TimeTick>
<NodeArgs eType="General" icon="0" nRep="26" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:01]]></Time>
<TimeTick>1597997881</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[11.1: Type John in First name textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:02]]></Time>
<TimeTick>1597997882</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[11.2: Type Smith in Last name textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:03]]></Time>
<TimeTick>1597997883</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Enter the learner's date... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:05]]></Time>
<TimeTick>1597997885</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11.3: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:05]]></Time>
<TimeTick>1597997885</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Enter the learner's date... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:06]]></Time>
<TimeTick>1597997886</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[12.1: Type 10 in Day textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:06]]></Time>
<TimeTick>1597997886</TimeTick>
<NodeArgs eType="General" icon="0" nRep="33" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[12.2: Type 10 in Month textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:07]]></Time>
<TimeTick>1597997887</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Enter the learner's date... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:08]]></Time>
<TimeTick>1597997888</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[12.3: Type 2000 in Year textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:08]]></Time>
<TimeTick>1597997888</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Select the provider label exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:10]]></Time>
<TimeTick>1597997890</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12.4: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:10]]></Time>
<TimeTick>1597997890</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Select Barking & Dagenham College (10000528) from Select the provider listbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:11]]></Time>
<TimeTick>1597997891</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Select the core label exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:13]]></Time>
<TimeTick>1597997893</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:13]]></Time>
<TimeTick>1597997893</TimeTick>
<NodeArgs eType="General" icon="0" nRep="41" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[15: Select Catering and Hospitality (11011011) from Select the core listbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:14]]></Time>
<TimeTick>1597997894</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Has the learner decided... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:16]]></Time>
<TimeTick>1597997896</TimeTick>
<NodeArgs eType="General" icon="0" nRep="43" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[16: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:16]]></Time>
<TimeTick>1597997896</TimeTick>
<NodeArgs eType="General" icon="0" nRep="44" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[17: Select Yes, add the specialism now from Yes, add the specialism... radiogroup was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:16]]></Time>
<TimeTick>1597997896</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Select the specialisms... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:18]]></Time>
<TimeTick>1597997898</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[18: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:19]]></Time>
<TimeTick>1597997899</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[19: Click on Catering  was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:19]]></Time>
<TimeTick>1597997899</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Select the academic year label exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:21]]></Time>
<TimeTick>1597997901</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[20: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:22]]></Time>
<TimeTick>1597997902</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Check and submit heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:23]]></Time>
<TimeTick>1597997903</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[21: Click on Continue button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:24]]></Time>
<TimeTick>1597997904</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Registration successful heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:25]]></Time>
<TimeTick>1597997905</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[23: Click on Submit button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:26]]></Time>
<TimeTick>1597997906</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Registrations heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:28]]></Time>
<TimeTick>1597997908</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[24: Click on Back to registrations button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:28]]></Time>
<TimeTick>1597997908</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Search for a registration heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:30]]></Time>
<TimeTick>1597997910</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[25: Click on Search for a registration link was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:30]]></Time>
<TimeTick>1597997910</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[26: Click on Enter the Unique Learner... textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:31]]></Time>
<TimeTick>1597997911</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[27: Type 8434823482 in Enter the Unique Learner... textbox was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:32]]></Time>
<TimeTick>1597997912</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Registration details heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:34]]></Time>
<TimeTick>1597997914</TimeTick>
<NodeArgs eType="General" icon="0" nRep="61" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[28: Click on Search button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:34]]></Time>
<TimeTick>1597997914</TimeTick>
<NodeArgs eType="General" icon="0" nRep="62" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Are you sure you want... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:36]]></Time>
<TimeTick>1597997916</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[29: Click on Cancel this registration button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:36]]></Time>
<TimeTick>1597997916</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[30: Select Yes, cancel registration from Yes, cancel registration... radiogroup was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:37]]></Time>
<TimeTick>1597997917</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Registration cancelled... heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:39]]></Time>
<TimeTick>1597997919</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[32: Click on Submit button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:39]]></Time>
<TimeTick>1597997919</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[: Wait until Registrations heading exists was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:41]]></Time>
<TimeTick>1597997921</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[33: Click on Back to registrations button was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:41]]></Time>
<TimeTick>1597997921</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[34: Click on Sign out link was finished]]></Details>
<Time><![CDATA[21/08/2020 - 09:18:43]]></Time>
<TimeTick>1597997923</TimeTick>
<NodeArgs eType="General" icon="0" nRep="70" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="21/08/2020 - 09:17:36" eTime="21/08/2020 - 09:18:43" passed="62" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[TruClient2 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T67">
<AName><![CDATA[End]]></AName>
<Summary sTime="21/08/2020 - 09:18:43" eTime="21/08/2020 - 09:18:43" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="73" >
<Disp><![CDATA[End Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="21/08/2020 - 09:17:31" eTime="21/08/2020 - 09:18:49" passed="62" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test TruClient2 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>